name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black isort flake8 mypy pylint
        
    - name: Format code with black
      run: |
        black --check --diff .
        
    - name: Sort imports with isort
      run: |
        isort --check-only --diff .
        
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Type checking with mypy
      run: |
        mypy . --ignore-missing-imports --no-strict-optional
        
    - name: Lint with pylint
      run: |
        pylint streamlit_app.py main.py --disable=C0114,C0116
        
    - name: Check for TODO comments
      run: |
        if grep -r "TODO" . --exclude-dir=.git; then
          echo "Found TODO comments. Please address them."
          exit 1
        fi
        
    - name: Check for FIXME comments
      run: |
        if grep -r "FIXME" . --exclude-dir=.git; then
          echo "Found FIXME comments. Please address them."
          exit 1
        fi
